# Generated by Django 5.2.8 on 2025-11-06 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Método')),
            ],
            options={
                'verbose_name_plural': 'Métodos',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('VEGETARIANO', 'Vegetariano'), ('VEGANO', 'Vegano'), ('NENHUM', 'Nenhum')], max_length=15, verbose_name='Tipo')),
                ('porcoes', models.PositiveIntegerField(verbose_name='Porções')),
                ('tempo_preparo', models.PositiveIntegerField(help_text='Informe o tempo total necessário em minutos', verbose_name='Tempo de preparo (minutos)')),
                ('preparo', models.TextField(verbose_name='Preparo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categorias', models.ManyToManyField(to='receitas.categoria', verbose_name='Categorias')),
                ('metodos', models.ManyToManyField(to='receitas.metodo', verbose_name='Metodos')),
            ],
            options={
                'verbose_name_plural': 'Receitas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unidade', models.CharField(choices=[('ML', 'mls'), ('XICARA', 'Xicaras'), ('COLHER_SOPA', 'Colheres de sopa'), ('UNIDADE', 'unidades'), ('COLHER_CHA', 'Colheres de chá'), ('GRAMA', 'Gramas')], max_length=15, verbose_name='Unidade')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='receitas.receita')),
            ],
            options={
                'verbose_name_plural': 'Ingredientes',
            },
        ),
    ]
