# Generated by Django 5.2.8 on 2025-11-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidade',
            field=models.CharField(choices=[('ML', 'mls'), ('XICARA', 'Xicaras'), ('COLHER_SOPA', 'Colheres de sopa'), ('UNIDADE', 'unidades'), ('COLHER_CHA', 'Colheres de chá'), ('GRAMA', 'Gramas'), ('CAIXA', 'Caixas')], max_length=15, verbose_name='Unidade'),
        ),
    ]
