# Generated by Django 5.2.8 on 2025-11-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_alter_ingrediente_unidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['-nome'], 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='metodo',
            options={'ordering': ['-nome'], 'verbose_name_plural': 'Métodos'},
        ),
    ]
