# Generated by Django 5.2.8 on 2025-11-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_alter_categoria_options_alter_metodo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='estado',
            field=models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='PRIVADO', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tipo',
            field=models.CharField(choices=[('VEGETARIANO', 'Vegetariano'), ('VEGANO', 'Vegano'), ('NENHUM', 'Nenhum')], default='NENHUM', max_length=15, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem'), ('VIDEO', 'Video')], max_length=10, verbose_name='Tipo')),
                ('arquivo', models.FileField(upload_to='receitas/midias/', verbose_name='Arquivo')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='receitas.receita')),
            ],
            options={
                'verbose_name_plural': 'Mídias',
            },
        ),
    ]
