# Generated by Django 5.2.8 on 2025-11-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_receita_estado_alter_receita_tipo_midia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='arquivo',
            field=models.FileField(upload_to='receitas/media/', verbose_name='Arquivo'),
        ),
    ]
