# Generated by Django 5.2.8 on 2025-11-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_alter_midia_arquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='metodo',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Métodos'},
        ),
    ]
