# Generated by Django 5.2.8 on 2025-11-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_alter_categoria_options_alter_metodo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidade',
            field=models.CharField(choices=[('CAIXA', 'Caixa(s)'), ('COLHER_CHA', 'Colher(es) de chá'), ('COLHER_SOPA', 'Colher(es) de sopa'), ('GRAMA', 'Grama(s) / g(s)'), ('ML', 'Mililitro(s) / mL(s)'), ('OPCIONAL', 'A gosto'), ('UNIDADE', 'unidade(s)'), ('XICARA', 'Xicara(s)')], max_length=15, verbose_name='Unidade'),
        ),
    ]
