# Generated by Django 5.2.8 on 2025-11-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0008_alter_ingrediente_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='arquivo',
            field=models.FileField(upload_to='receitas/', verbose_name='Arquivo'),
        ),
    ]
