# Generated by Django 5.2.8 on 2025-11-18 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0011_alter_receita_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='preparo',
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparo', to='receitas.receita')),
            ],
            options={
                'verbose_name_plural': 'Preparo',
                'ordering': ['id'],
            },
        ),
    ]
