# Generated by Django 5.2.8 on 2025-11-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0012_remove_receita_preparo_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='opcional',
            field=models.BooleanField(default=False, verbose_name='Opcional'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidade',
            field=models.CharField(choices=[('CAIXA', 'Caixa(s)'), ('COLHER_CHA', 'Colher(es) de chá'), ('COLHER_SOPA', 'Colher(es) de sopa'), ('GRAMA', 'Grama(s) / g(s)'), ('ML', 'Mililitro(s) / mL(s)'), ('UNIDADE', 'unidade(s)'), ('XICARA', 'Xicara(s)')], max_length=15, verbose_name='Unidade'),
        ),
    ]
