# Generated by Django 5.2.8 on 2025-11-21 21:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0013_ingrediente_opcional_alter_ingrediente_unidade'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='quantidade',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidade',
            field=models.CharField(choices=[('CAIXA', 'caixa(s)'), ('COLHER_CHA', 'colher(es) de chá'), ('COLHER_SOPA', 'colher(es) de sopa'), ('COPO', 'copo(s)'), ('GRAMA', 'Grama(s) / g(s)'), ('MILILITRO', 'Mililitro(s) / mL(s)'), ('UNIDADE', 'unidade(s)'), ('XICARA', 'xicara(s)')], max_length=15, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_autor', to='usuarios.perfil', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categorias',
            field=models.ManyToManyField(related_name='receitas_categoria', to='receitas.categoria', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='metodos',
            field=models.ManyToManyField(related_name='receitas_metodo', to='receitas.metodo', verbose_name='Metodos'),
        ),
        migrations.AddConstraint(
            model_name='ingrediente',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 0.0)), name='quantidade_positiva_ingrediente'),
        ),
    ]
