# Generated by Django 5.2.8 on 2025-11-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0014_alter_receita_options_alter_ingrediente_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['id'], 'verbose_name_plural': 'Etapas'},
        ),
        migrations.AlterField(
            model_name='etapa',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='receitas.receita'),
        ),
    ]
