# Generated by Django 5.2.8 on 2025-11-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0015_alter_etapa_options_alter_etapa_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='arquivo',
            field=models.FileField(max_length=500, upload_to='receitas/', verbose_name='Arquivo'),
        ),
    ]
