# Generated by Django 5.2.8 on 2025-11-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0016_alter_midia_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidade',
            field=models.CharField(choices=[('CAIXA', 'caixa(s)'), ('COLHER_CHA', 'colher(es) de chá'), ('COLHER_SOPA', 'colher(es) de sopa'), ('COPO', 'copo(s)'), ('GRAMA', 'grama(s) / g(s)'), ('LATA', 'lata(s)'), ('MILILITRO', 'mililitro(s) / mL(s)'), ('UNIDADE', 'unidade(s)'), ('XICARA', 'xicara(s)')], max_length=15, verbose_name='Unidade'),
        ),
    ]
