# Generated by Django 5.2.8 on 2025-11-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0017_alter_ingrediente_unidade'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_favorito', to='receitas.receita', verbose_name='Favoritos'),
        ),
    ]
